#!/bin/bash
module load vasp/5.4.1

cd /afs/crc.nd.edu/user/w/wschnei1/Group/People/jcrum/CBE60547/Lab3
cd /afs/crc.nd.edu/user/w/wschnei1/Group/People/jcrum/CBE60547/Lab3/molecules/co-L-6  # this is the vasp directory

runvasp.py     # this is the vasp command
#end
