#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CHE 60547 Syllabus
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
# #+LATEX_HEADER:\setlength{\headheight}{10.2pt}
# #+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2019 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\title{University of Notre Dame\\Computationl Chemistry\\(CBE 40447/60547)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\usepackage[small]{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.0\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.0\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.1\baselineskip}{0.0\baselineskip}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

#+BEGIN_EXPORT latex
\begin{center}
\textsc{\Large Computational Chemistry (CBE 60547)}\\University of Notre Dame, Fall 2019
\end{center}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l r}
\hline
Prof.\ Bill Schneider & Classroom: B011 DBRT\\
Office: 370 NSH & Lecture MWF 12:50-1:40\\
\email{wschneider@nd.edu}, phone 574-631-8754\\
\hline
\end{tabular*}
#+END_EXPORT

* Computational Chemistry
Atomic-scale, simulations have exploded in importance in the last twenty years, largely because of the exponential growth in computing power available to researchers. Chemists, chemical engineers, materials scientists, physicists, geochemists, environmental scientists, ..., now all use atomic scale simulations of one type or another to solve scientific and engineering problems and advance their fields. In fact, the topic is now so broad that it is impossible to capture with one name or to cover completely in one course.

Our emphasis in this course will be on modern approaches to calculating chemical properties using quantum-mechanics-based atomistic simulations. The emphasis is on application rather than theory, but with the recognition that it is impossible to be an intelligent practitioner without some appreciation of underlying theory. I won’t make any assumptions about your prior knowledge beyond what is typically covered in an undergraduate Physical Chemistry course. 
** Learning goals
1. Understand the basic theoretical, mathematical, and numerical concepts behind  first-principles quantum-mechanics-based calculations.
2. Understand the terminology and practical issues associated with executing and applying these calculations.
3. Gain hand-on experience with these concepts using popular computational tools of today, including /GAMESS/ for molecular systems and /Vasp/ for periodic systems.
4. Learn to interface the results of quantum mechanical calculations with statistical mechanical theories to calculate thermodynamic and kinetic parameters.
5. Propose, execute, and report out on your own computational project.

* Web
All materials for the course are shared at [[https://github.com/wmfschneider/CBE60547]].  If you want to get your own copy of all this material and understand a bit about how git works, see [[http://rogerdudler.github.io/git-guide/]].  Or just download files directly from the git site. The source files are written using Org Mode ([[https://orgmode.org/]]), but you can read them using a regular text editor if you want to see under the hood.

* Useful Texts
1. A chemistry take on methods: Chris Cramer, /Essentials of Computational Chemistry/, Wiley, 2004

2. A chemical engineering take: David Sholl and Jan Steckel, /Density Functional Theory: A Practical Introduction/, Wiley, 2009

3. Hard-core DFT theory: Richard Martin, /Electronic Structure/, Cambridge, 2004

* Hands-on
You all either have or will get accounts on the Notre Dame Center for Reseach Computing ([[http://crc.nd.edu]]) computers. We will have four in-class, hands-on sessions to illustrate access and use of these resources, which will be necessary for completing the homework and independent project. 

* Grading
Grades will be based on homework assignments (50%), an in-class exam (10%), and a class project and report (40%).  Attendance and participation is expected.

* Academic honesty
Should go without saying. Any cheating or misrepresenting of work as your own will be dealt with according to the Honor Code policies of the university. I reserve the right to relocate any students during an examination at my discretion.

* Professional courtesy
As a courtesy to the instructor and your classmates, please refrain from
texting, web browsing, tweeting, chatting, updating, or using your phone or laptop for any
purpose during class time.  If you must use an electronic device, excuse
yourself from class.

* Office hours
The instructor is happy to answer questions by appointment, or just stop by!
