#+TITLE:
#+AUTHOR:
#+DATE: Due: <2019-12-09 Mon>
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt]
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_HEADER: \usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage[labelfont=bf]{caption}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage[parfill]{parskip}
#+LATEX_HEADER: \usepackage[version=3]{mhchem}

\title{In Class\\Computational Chemistry\\(CBE 60547)}
\author{Prof.\ William F.\ Schneider}
\maketitle

Describe the computational approach you would take to answer the question. Be sure to detail all the calculations you would need and how you would combine them to arise at an answer. Indicate any sources of uncertainty in your predictions.
* Group 1: Particle Shape
Your collaborator is going to prepare large(ish) particles of Au (an FCC metal) on an inert support (say MgO). What shape(s) do you expect the particle to adopt? 

* Group 2: Alloy phase diagram
Au and Cu both crystallize as FCC metals. Do you expect them to form ordered compounds or a disordered, random alloy? Does the answer depend on temperature?

* Group 3: Surface adsorption
Your colleague has two Pd single crystals, (111) and (100) facets, but can't remember which is which. She has a cylinder of CO that she can dose to the crystals. What calculations can you do to help her distinguish the two crystals. Identify at least two.

* Group 4: Segregation
Your colleague prepares a 90/10 (by mole number) Pt/Au alloy crystal and cleaves to expose a (111) facet. Do you expect the surface to have the same composition as the bulk, or be enriched in Pt, or in Au (at equilibrium)?  Does the answer depend on whether the measurement is made in vacuum or in CO?
