#+TITLE:Computational Chemistry Laboratory II (CBE 60547)
#+AUTHOR: Prateek Mehta, William F. Schneider
#+DATE:02-05-2015 Thu
#+LATEX_CLASS: article
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_HEADER: \usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry} 
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage[labelfont=bf]{caption}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage[parfill]{parskip}

\maketitle

* Electronic Structure Calculations using =GAMESS= and =Avogadro=

In this lab session we will learn how to run and visualize the results of electronic structure calculations utilizing the GAMESS and Avogadro software on the CRC machines.

** Logging In

You should all be familiar with how to login to the CRC front end machine.

- Windows users using putty, open it and login.

- For Mac and Linux users, and for windows users using MobaXterm,

#+BEGIN_SRC sh
ssh -Y yournetid@crcfe01.crc.nd.edu
#+END_SRC

** Loading the required modules

- The shell command ~module avail~ shows a list of software installed on the CRC machines which you can load and use

#+BEGIN_SRC sh
module avail
#+END_SRC


- The modules we will need to load are ~avogadro~, ~gamess~, and ~openbabel~.

#+BEGIN_SRC sh
module load avogadro
module load gamess
module load openbabel
#+END_SRC

** Avogadro

- To launch avogadro type

#+BEGIN_SRC sh
avogadro &
#+END_SRC

#+RESULTS:

- We are going to set up and run a calculation for N_{2}

- In the draw settings section select nitrogen from the element drop down menu

- Uncheck adjust hydrogens (this will put hydrogens on your atom and construct NH_{3})

- Clicking in the view window will create a nitrogen atom

- Place two nitrogen atoms next to each other to make a N_{2} molecule

- Hovering over any of the icons in the top bar will display a description of that option.

- The click to measure tool will allow you to measure distances (select two atoms) and angles (select 3 atoms). Select both nitrogens, #1 and #2 will appear on them and the distance will be displayed below

- Click on the manipulation tool (the hand with a finger pointing)

- Click and drag one of the nitrogens until the bond length is 1.1 ˚A (later we will learn methods for optimizing geometry, but for right now we will set it based on the experimental distance http://cccbdb.nist.gov/exp2.asp?casno=7727379)

** =GAMESS=

*** Creating Input files

- We are ready to generate our input file now. From the extensions menu select =GAMESS= and click on =Input Generator=

- A window will pop-up. The setup for this calculation right now is a single point energy calculation, the method is restricted Hartree-Fock, with the STO-3G basis. In the lower right click generate

- Name your input file and save it in a new folder

- Alternately, you could also have typed in the input file by hand 

*** Running calculations

- Go back to the terminal cd into the directory where you saved the input file

- The command below will run games on your input file and generate an output file called =N2.log=

#+BEGIN_SRC sh
rungms N2.inp > N2.log
#+END_SRC



*** Analyzing the output

- Open the output file in a text editor 

#+BEGIN_SRC sh
emacs N2.log &
#+END_SRC

- The structure of the output file is
  - summary of the input
  - initialization messages
  - store 1 and 2 electron integrals
  - SCF calculation details
  - final orbital populations and energies

- Now go back to Avogadro and open the log file

- From here you can view the orbitals and their energies

- You can also measure any angles and bond lengths in the same manner as we did when setting up the input calculation

