#+TITLE:
#+AUTHOR:
#+DATE:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt]
#+OPTIONS: ^:{} # make super/subscripts only when wrapped in {}
#+OPTIONS: toc:nil # suppress toc, so we can put it where we want
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

#+LATEX_HEADER: \usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage[labelfont=bf]{caption}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \usepackage{siunitx}
#+LATEX_HEADER: \usepackage[parfill]{parskip}
#+LATEX_HEADER: \usepackage[version=3]{mhchem}

\title{CBE 60547 Computational Chemistry Class Project}
\maketitle

* Project
The purpose of the class project is to give you a chance to creatively apply the knowledge you have gained in the course of the semester about first-principles modeling of chemical systems to a short research problem of your own choosing.  I hope it is something you can have fun in selecting and carrying out.  The research problem can be of several types:

a. A particular chemical problem that you would like to investigate, perhaps related to your own research interests or research project.
b. A particular computational issue you would like to explore, such as the relative performance of some methods (GGA vs MP2, basis convergence, ...) or algorithms for a particular type of calculation.
c. A particular theoretical issue you would like to address, perhaps elaborating on a topic that we didn't have time to develop in class (e.g., solvation effects, excited states, NMR, ...)

* Requirements:
1. *Due November 4, 2019 (10%)* Provide in pdf, via upload, a brief (1 page) description of your proposed class project.  Include (1) background about the problem area, including any relevant references, (2) the specific research question you propose to address, and (3) the computational plan for answering the research question. You may discuss this plan with Schneider before the due date. You will receive feedback and suggestions shortly after you turn in the proposal.
2. *Due November 25, 2019 (10%)* Provide in pdf, via upload, a brief (2 page) summary of preliminary computational results, in particular highlighting any difficulties you have encountered.
3. *Due December 13, 2019 (80%)* Your pdf report will include an approximately six-page write-up of your project and results and analysis.  The scientific and intellectual completeness is more important than any particular length. Include:
   1. (5 pts) _Cover page_ with title and name.
   2. (15 pts) _Introduction_ to the problem area and specific question you are addressing.
   3. (10 pts) _Computational methods_ applied (software, methods, basis sets, etc.)
   4. (20 pts) _Results_ of your project, including descriptive narrative, Tables and Figures, as appropriate.
   5. (15 pts) _Discussion_ of the outcomes and suggested future work.
   6. (5 pts) _Conclusions_ summarizing outcomes and suggested future work.
   7. (5 pts) _References cited_
   8. (5 pts) _Appendix_ including scripts  from your calculations and from creating figures and tables. Ideally, provide sufficient details that someone else could reproduce the reported results.

Your grade will be based on the appropriateness of your question, the thoughtfulness and execution of the approach, and the quality and thoughtfulness of the report of your results.

* Samples from past years
1. Computational determination of isothermal compressibility of simple salts
2. Characterization of the diffusion of tritium into bulk tungsten
3. Interaction between ionic liquids and water
4. Methanol force field parameters
5. DFT study of cerium-doped SSZ-13 and H-Ce-SSZ-13
6. Ligand-metal coordination of a tridentate borate ligand
7. Interactions in liquid-liquid equilibria of toluene-sulfalone
8. Adsorption of aqueous ammonia-borane on transition-metal surfaces
9. Development of classical force field based on REBO potential for graphene heat spreader
10. United atom force field for polyethylene glycol thiol (thiolated PEG)
11. Deprotonation energies
12. Diatomic charge densities from artifical neural networks
13. Adsorption energies of N-nitrosodimethylamine on Pd@Ni and Ni@Pd core-shell particles
14. Computational studies of CO2 with choliniums
15. Ethane radical reaction: a comparison of methyl radical termination and hydrogen abstraction
16. Amino acid zwitterions: an investigation into the modern computational methods of solvation
17. GGA calculation of strain effects on SrTiO3 band structure
